from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import render, redirect

from hostel.models import Student


# ==========================================================
# PUBLIC HOME PAGE
# ==========================================================

def home(request):
    """
    Public home page of DIDI BAHINI GIRLS HOSTEL.
    """

    return render(
        request,
        'home/home.html'
    )


# ==========================================================
# STUDENT ID GENERATOR
# ==========================================================

def generate_student_id():
    """
    Generate the next available Student ID.

    Format:

        DBH-001
        DBH-002
        DBH-003
        DBH-004

    Existing Student IDs are checked so that the generated
    ID is not duplicated.
    """

    existing_ids = Student.objects.values_list(
        'student_id',
        flat=True
    )

    used_numbers = []

    for student_id in existing_ids:

        if not student_id:
            continue

        student_id = student_id.strip()

        if student_id.upper().startswith('DBH-'):

            number_part = student_id[4:]

            if number_part.isdigit():

                used_numbers.append(
                    int(number_part)
                )

    next_number = 1

    while next_number in used_numbers:

        next_number += 1

    return f'DBH-{next_number:03d}'


# ==========================================================
# STUDENT REGISTRATION
# ==========================================================

def register_view(request):
    """
    Register a new hostel student.

    Student ID is automatically generated by the system.

    Example:

        DBH-001
        DBH-002
        DBH-003

    Students cannot manually change the generated ID.
    """

    # ------------------------------------------------------
    # ALREADY LOGGED-IN USER
    # ------------------------------------------------------

    if request.user.is_authenticated:

        if request.user.is_superuser:

            return redirect(
                'admin_dashboard'
            )

        return redirect(
            'student_dashboard'
        )

    # ------------------------------------------------------
    # GENERATE STUDENT ID FOR REGISTRATION PAGE
    # ------------------------------------------------------

    generated_student_id = generate_student_id()

    # ------------------------------------------------------
    # HANDLE REGISTRATION FORM
    # ------------------------------------------------------

    if request.method == 'POST':

        # ==================================================
        # ACCOUNT INFORMATION
        # ==================================================

        username = request.POST.get(
            'username',
            ''
        ).strip()

        password = request.POST.get(
            'password',
            ''
        )

        # ==================================================
        # PERSONAL INFORMATION
        # ==================================================

        full_name = request.POST.get(
            'full_name',
            ''
        ).strip()

        email = request.POST.get(
            'email',
            ''
        ).strip()

        phone = request.POST.get(
            'phone',
            ''
        ).strip()

        address = request.POST.get(
            'address',
            ''
        ).strip()

        # ==================================================
        # GUARDIAN INFORMATION
        # ==================================================

        guardian_name = request.POST.get(
            'guardian_name',
            ''
        ).strip()

        guardian_phone = request.POST.get(
            'guardian_phone',
            ''
        ).strip()

        # ==================================================
        # ALWAYS GENERATE STUDENT ID FROM SERVER
        # ==================================================

        student_id = generate_student_id()

        # ==================================================
        # REQUIRED FIELD VALIDATION
        # ==================================================

        if not username or not password:

            messages.error(
                request,
                'Username and password are required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not full_name:

            messages.error(
                request,
                'Full name is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not email:

            messages.error(
                request,
                'Email address is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not phone:

            messages.error(
                request,
                'Phone number is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not address:

            messages.error(
                request,
                'Address is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not guardian_name:

            messages.error(
                request,
                'Guardian name is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        if not guardian_phone:

            messages.error(
                request,
                'Guardian phone number is required.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        # ==================================================
        # USERNAME VALIDATION
        # ==================================================

        if User.objects.filter(
            username=username
        ).exists():

            messages.error(
                request,
                'Username already exists. Please choose another username.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        # ==================================================
        # STUDENT ID VALIDATION
        # ==================================================

        if Student.objects.filter(
            student_id=student_id
        ).exists():

            student_id = generate_student_id()

            messages.warning(
                request,
                f'A new Student ID has been generated: {student_id}'
            )

        # ==================================================
        # EMAIL VALIDATION
        # ==================================================

        if User.objects.filter(
            email__iexact=email
        ).exists():

            messages.error(
                request,
                'This email address is already registered.'
            )

            return render(
                request,
                'accounts/register.html',
                {
                    'generated_student_id': student_id
                }
            )

        # ==================================================
        # CREATE DJANGO USER
        # ==================================================

        user = User.objects.create_user(
            username=username,
            email=email,
            password=password,
            first_name=full_name
        )

        # ==================================================
        # CREATE STUDENT PROFILE
        # ==================================================

        Student.objects.create(
            user=user,
            student_id=student_id,
            full_name=full_name,
            phone=phone,
            email=email,
            address=address,
            guardian_name=guardian_name,
            guardian_phone=guardian_phone,
            gender='Female'
        )

        # ==================================================
        # REGISTRATION SUCCESS MESSAGE
        # ==================================================

        messages.success(
            request,
            f'Registration successful. Your Student ID is {student_id}. Please login.'
        )

        # ==================================================
        # REDIRECT TO STUDENT LOGIN
        # ==================================================

        return redirect(
            'login'
        )

    # ======================================================
    # DISPLAY REGISTRATION PAGE
    # ======================================================

    return render(
        request,
        'accounts/register.html',
        {
            'generated_student_id': generated_student_id
        }
    )


# ==========================================================
# STUDENT LOGIN
# ==========================================================

def login_view(request):
    """
    Login page for normal hostel students.

    IMPORTANT ACCESS RULES:

    1. Normal student credentials:
       Login successfully and go to student dashboard.

    2. Administrator credentials:
       Completely blocked from this page.
       The administrator is NOT logged in.
       The administrator is NOT redirected to /admin/.
       The administrator remains on the student login page.

    3. Invalid credentials:
       Remain on the student login page.
    """

    # ------------------------------------------------------
    # ALREADY LOGGED-IN USER
    # ------------------------------------------------------

    if request.user.is_authenticated:

        # --------------------------------------------------
        # ADMINISTRATOR ALREADY LOGGED IN
        # --------------------------------------------------

        if request.user.is_superuser:

            return redirect(
                'admin_dashboard'
            )

        # --------------------------------------------------
        # NORMAL STUDENT ALREADY LOGGED IN
        # --------------------------------------------------

        return redirect(
            'student_dashboard'
        )

    # ------------------------------------------------------
    # HANDLE LOGIN FORM
    # ------------------------------------------------------

    if request.method == 'POST':

        username = request.POST.get(
            'username',
            ''
        ).strip()

        password = request.POST.get(
            'password',
            ''
        )

        # ==================================================
        # EMPTY FIELD VALIDATION
        # ==================================================

        if not username or not password:

            messages.error(
                request,
                'Please enter both username and password.'
            )

            return render(
                request,
                'accounts/login.html'
            )

        # ==================================================
        # AUTHENTICATE USER
        # ==================================================

        user = authenticate(
            request,
            username=username,
            password=password
        )

        # ==================================================
        # INVALID LOGIN
        # ==================================================

        if user is None:

            messages.error(
                request,
                'Invalid student username or password.'
            )

            return render(
                request,
                'accounts/login.html'
            )

        # ==================================================
        # BLOCK ADMINISTRATOR FROM STUDENT LOGIN
        # ==================================================

        if user.is_superuser:

            messages.error(
                request,
                'Administrator accounts cannot use the student login page.'
            )

            # IMPORTANT:
            #
            # Do NOT call login().
            #
            # Do NOT redirect to admin_login.
            #
            # Render the same student login page.
            #
            return render(
                request,
                'accounts/login.html'
            )

        # ==================================================
        # CHECK STUDENT PROFILE
        # ==================================================

        if not hasattr(
            user,
            'student_profile'
        ):

            messages.error(
                request,
                'Student profile not found. Please contact the hostel administrator.'
            )

            return render(
                request,
                'accounts/login.html'
            )

        # ==================================================
        # LOGIN STUDENT
        # ==================================================

        login(
            request,
            user
        )

        # ==================================================
        # SUCCESS MESSAGE
        # ==================================================

        messages.success(
            request,
            'Login successful. Welcome to DIDI BAHINI GIRLS HOSTEL.'
        )

        # ==================================================
        # STUDENT DASHBOARD
        # ==================================================

        return redirect(
            'student_dashboard'
        )

    # ======================================================
    # DISPLAY STUDENT LOGIN PAGE
    # ======================================================

    return render(
        request,
        'accounts/login.html'
    )


# ==========================================================
# ADMINISTRATOR LOGIN
# ==========================================================

def admin_login_view(request):
    """
    Custom administrator login page.

    URL:

        /admin/

    Only Django superusers are allowed to login here.

    Successful administrator login redirects to:

        /dashboard/admin/
    """

    # ------------------------------------------------------
    # ALREADY LOGGED-IN USER
    # ------------------------------------------------------

    if request.user.is_authenticated:

        # --------------------------------------------------
        # ADMINISTRATOR
        # --------------------------------------------------

        if request.user.is_superuser:

            return redirect(
                'admin_dashboard'
            )

        # --------------------------------------------------
        # NORMAL STUDENT CANNOT ACCESS ADMIN PORTAL
        # --------------------------------------------------

        messages.warning(
            request,
            'Student accounts cannot access the administrator portal.'
        )

        return redirect(
            'student_dashboard'
        )

    # ------------------------------------------------------
    # HANDLE ADMIN LOGIN FORM
    # ------------------------------------------------------

    if request.method == 'POST':

        username = request.POST.get(
            'username',
            ''
        ).strip()

        password = request.POST.get(
            'password',
            ''
        )

        # ==================================================
        # EMPTY FIELD VALIDATION
        # ==================================================

        if not username or not password:

            messages.error(
                request,
                'Please enter administrator username and password.'
            )

            return render(
                request,
                'accounts/admin_login.html'
            )

        # ==================================================
        # AUTHENTICATE ADMINISTRATOR
        # ==================================================

        user = authenticate(
            request,
            username=username,
            password=password
        )

        # ==================================================
        # INVALID ADMIN LOGIN
        # ==================================================

        if user is None:

            messages.error(
                request,
                'Invalid administrator username or password.'
            )

            return render(
                request,
                'accounts/admin_login.html'
            )

        # ==================================================
        # BLOCK NORMAL STUDENT
        # ==================================================

        if not user.is_superuser:

            messages.error(
                request,
                'Access denied. This account is not an administrator account.'
            )

            return render(
                request,
                'accounts/admin_login.html'
            )

        # ==================================================
        # LOGIN ADMINISTRATOR
        # ==================================================

        login(
            request,
            user
        )

        # ==================================================
        # ADMIN LOGIN SUCCESS MESSAGE
        # ==================================================

        messages.success(
            request,
            'Welcome to the DIDI BAHINI GIRLS HOSTEL Administrator Dashboard.'
        )

        # ==================================================
        # ADMIN DASHBOARD
        # ==================================================

        return redirect(
            'admin_dashboard'
        )

    # ======================================================
    # DISPLAY ADMIN LOGIN PAGE
    # ======================================================

    return render(
        request,
        'accounts/admin_login.html'
    )


# ==========================================================
# LOGOUT
# ==========================================================

def logout_view(request):
    """
    Logout the currently authenticated user.

    After logout, the user is redirected to the public
    Home page.
    """

    # ------------------------------------------------------
    # LOGOUT CURRENT USER
    # ------------------------------------------------------

    logout(
        request
    )

    # ------------------------------------------------------
    # LOGOUT SUCCESS MESSAGE
    # ------------------------------------------------------

    messages.success(
        request,
        'You have been logged out successfully.'
    )

    # ------------------------------------------------------
    # REDIRECT TO HOME
    # ------------------------------------------------------

    return redirect(
        'home'
    )
