# Generated by Django 5.2.3 on 2026-10-06 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='send_to_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='received_notices', to='hostel.student'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hostel_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
